services:
  api:
    image: mcr.microsoft.com/devcontainers/java:17
    volumes:
      - .:/workspaces/${localWorkspaceFolderBasename}
    command: sleep infinity
    depends_on:
      - db
    networks: [appnet]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [appnet]

volumes:
  dbdata:

networks:
  appnet:
